spring.application.name=familia
spring.datasource.url=jdbc:mysql://localhost:3306/familia_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.open-in-view=false

server.port=${PORT:8080}

# Mailpit (SMTP) - http://localhost:8025
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# URLs (pour liens dans les emails)
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:4200}


app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-seconds=86400

app.upload.dir=uploads/personnes